#!/bin/bash

__red_style_blockarrow_module() {
  if __red_powerline; then
    echo -n '{reverse} '
  else
    echo -n '{reverse} '
  fi
}

__red_style_blockarrow_module_end() {
  if __red_powerline; then
    echo -n ' {/reverse}'
  else
    echo -n ' '
  fi
}

__red_style_blockarrow_module_pad() {
  if ! __red_powerline; then
    echo -n ' '
  fi
}

