#!/usr/bin/env bash

if ! which terraform &>/dev/null; then
  red::set module_terraform_error "Unable to locate terraform"
  return 1
fi

red::module::terraform() {

  [[ -e .terraform/ ]] || return

  IFS='' read -r workspace < <(cat .terraform/environment 2>/dev/null)

  [[ "$workspace" == '' ]] && workspace="default"

  red::set module_terraform_content "$workspace"
  red::set module_terraform_color '#C3F'
  red::set module_terraform_symbol_unicode 'ⓣ '
  red::set module_terraform_symbol_ascii 'tf:'

}

