#!/usr/bin/env bash

if ! which virtualenv &>/dev/null; then
  red::set module_virtualenv_error "Unable to locate virtualenv"
  return 1
fi

red::module::virtualenv() {

  IFS='' read -r venv < <(basename "$VITURAL_ENV" 2>/dev/null)

  [[ "$venv" ]] || return

  red::set module_virtualenv_content "$venv"
  red::set module_virtualenv_color '#C90'
  red::set module_virtualenv_symbol_unicode '🐍'
  red::set module_virtualenv_symbol_ascii 'venv:'

}

